services:
  webserver:
    image: ghcr.io/oliumbi/webserver:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ../example:/example
    environment:
      - CONFIGURATION_PATH=./example/server.toml
