headless = true

[server]
threads = 8
timeout = 1

[[routes]]

[routes.path.Exact]
exact = "/"
methods = "GET"

[routes.action.Redirect]
location = "index.html"
status_code = 307

[[routes]]

[routes.path.Regex]
regex = "/(jublawoma|jublawoma-admin|unclet-admin|oliumbi-admin)"

[routes.action.Proxy]
location = "localhost:8080"

[[routes]]

[routes.path.Prefix]
prefix = "/"
methods = "GET,POST"

[routes.action.Fixed]
root = "./example/demo/"
fallback = "./notfound.html"
