#[derive(Debug)]
pub enum Method {
    Acl,
    BaselineControl,
    Bind,
    Checkin,
    Checkout,
    Connect,
    Copy,
    Delete,
    Get,
    Head,
    Label,
    Link,
    Lock,
    Merge,
    MkActivity,
    MkCalendar,
    MkCol,
    MkRedirectRef,
    MkWorkspace,
    Move,
    Options,
    Orderpatch,
    Patch,
    Post,
    Pri,
    PropFind,
    PropPatch,
    Put,
    Query,
    Rebind,
    Report,
    Search,
    Trace,
    Unbind,
    Uncheckout,
    Unlink,
    Unlock,
    Update,
    UpdateRedirectRef,
    VersionControl,
}

impl Method {
    pub fn as_str(&self) -> &'static str {
        match self {
            Method::Acl => "ACL",
            Method::BaselineControl => "BASELINECONTROL",
            Method::Bind => "BIND",
            Method::Checkin => "CHECKIN",
            Method::Checkout => "CHECKOUT",
            Method::Connect => "CONNECT",
            Method::Copy => "COPY",
            Method::Delete => "DELETE",
            Method::Get => "GET",
            Method::Head => "HEAD",
            Method::Label => "LABEL",
            Method::Link => "LINK",
            Method::Lock => "LOCK",
            Method::Merge => "MERGE",
            Method::MkActivity => "MKACTIVITY",
            Method::MkCalendar => "MKCALENDAR",
            Method::MkCol => "MKCOL",
            Method::MkRedirectRef => "MKREDIRECTREF",
            Method::MkWorkspace => "MKWORKSPACE",
            Method::Move => "MOVE",
            Method::Options => "OPTIONS",
            Method::Orderpatch => "ORDERPATCH",
            Method::Patch => "PATCH",
            Method::Post => "POST",
            Method::Pri => "PRI",
            Method::PropFind => "PROPFIND",
            Method::PropPatch => "PROPPATCH",
            Method::Put => "PUT",
            Method::Query => "QUERY",
            Method::Rebind => "REBIND",
            Method::Report => "REPORT",
            Method::Search => "SEARCH",
            Method::Trace => "TRACE",
            Method::Unbind => "UNBIND",
            Method::Uncheckout => "UNCHECKOUT",
            Method::Unlink => "UNLINK",
            Method::Unlock => "UNLOCK",
            Method::Update => "UPDATE",
            Method::UpdateRedirectRef => "UPDATEREDIRECTREF",
            Method::VersionControl => "VERSIONCONTROL",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s.to_uppercase().as_str() {
            "ACL" => Some(Method::Acl),
            "BASELINECONTROL" => Some(Method::BaselineControl),
            "BIND" => Some(Method::Bind),
            "CHECKIN" => Some(Method::Checkin),
            "CHECKOUT" => Some(Method::Checkout),
            "CONNECT" => Some(Method::Connect),
            "COPY" => Some(Method::Copy),
            "DELETE" => Some(Method::Delete),
            "GET" => Some(Method::Get),
            "HEAD" => Some(Method::Head),
            "LABEL" => Some(Method::Label),
            "LINK" => Some(Method::Link),
            "LOCK" => Some(Method::Lock),
            "MERGE" => Some(Method::Merge),
            "MKACTIVITY" => Some(Method::MkActivity),
            "MKCALENDAR" => Some(Method::MkCalendar),
            "MKCOL" => Some(Method::MkCol),
            "MKREDIRECTREF" => Some(Method::MkRedirectRef),
            "MKWORKSPACE" => Some(Method::MkWorkspace),
            "MOVE" => Some(Method::Move),
            "OPTIONS" => Some(Method::Options),
            "ORDERPATCH" => Some(Method::Orderpatch),
            "PATCH" => Some(Method::Patch),
            "POST" => Some(Method::Post),
            "PRI" => Some(Method::Pri),
            "PROPFIND" => Some(Method::PropFind),
            "PROPPATCH" => Some(Method::PropPatch),
            "PUT" => Some(Method::Put),
            "QUERY" => Some(Method::Query),
            "REBIND" => Some(Method::Rebind),
            "REPORT" => Some(Method::Report),
            "SEARCH" => Some(Method::Search),
            "TRACE" => Some(Method::Trace),
            "UNBIND" => Some(Method::Unbind),
            "UNCHECKOUT" => Some(Method::Uncheckout),
            "UNLINK" => Some(Method::Unlink),
            "UNLOCK" => Some(Method::Unlock),
            "UPDATE" => Some(Method::Update),
            "UPDATEREDIRECTREF" => Some(Method::UpdateRedirectRef),
            "VERSIONCONTROL" => Some(Method::VersionControl),
            _ => None,
        }
    }
}
