headless = false

[server]
threads = 8
timeout = 1

[[routes]]

[routes.path]
Exact = "/hello"

[routes.action.Redirect]
location = "index.html"
status_code = 307

[[routes]]

[routes.path]
Regex = "/(jublawoma|jublawoma-admin|unclet-admin|oliumbi-admin)"

[routes.action.Proxy]
location = "localhost:8080"

[[routes]]

[routes.path]
Prefix = "/"

[routes.action.Fixed]
root = "./examples/demo/"
fallback = "./notfound.html"
